openapi: 3.0.0
info:
  version: 1.0.0
  title: Kids Keeper API Docs
  description: Kids Keeper API 문서
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: dev servers
    url: 'http://localhost:3000/api/'
paths:
  /districts:
    get:
      tags:
        - district
      summary: get all districts
      description: null
      parameters:
        - name: parent_code
          in: query
          required: false
          description: 상위 행정구역 코드
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                    name:
                      type: string
                    parent_code:
                      type: string
                    count:
                      type: string
  '/districts/{code}':
    get:
      tags:
        - district
      summary: get district by code
      description: null
      parameters:
        - name: code
          in: path
          required: true
          description: 행정구역 코드
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  name:
                    type: string
                  parent_code:
                    type: string
                  count:
                    type: string
  '/districts/{name}':
    get:
      tags:
        - district
      summary: get district by name
      description: null
      parameters:
        - name: name
          in: path
          required: true
          description: 행정구역 이름
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  name:
                    type: string
                  parent_code:
                    type: string
                  count:
                    type: string
  /centers:
    get:
      tags:
        - children care center
      summary: get all centers
      description: null
      parameters:
        - name: code
          in: query
          required: false
          description: 행정구역 코드
        - name: name
          in: query
          required: false
          description: 행정구역 이름
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    center_id:
                      type: integer
                    name:
                      type: string
                    lat:
                      type: string
                    lng:
                      type: string
                    district_code:
                      type: string
                    district_name:
                      type: string
  '/centers/{id}':
    get:
      tags:
        - children care center
      summary: get center by center id
      description: null
      parameters:
        - name: id
          in: path
          required: true
          description: 어린이집 ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  center_id:
                    type: integer
                  name:
                    type: string
                  lat:
                    type: string
                  lng:
                    type: string
                  district_code:
                    type: string
                  district_name:
                    type: string
  '/centers/{name}':
    get:
      tags:
        - children care center
      summary: get center by name
      description: null
      parameters:
        - name: name
          in: path
          required: true
          description: 어린이집 이름
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  center_id:
                    type: integer
                  name:
                    type: string
                  lat:
                    type: string
                  lng:
                    type: string
                  district_code:
                    type: string
                  district_name:
                    type: string
tags:
  - name: district
  - name: children care center
