openapi: 3.0.0
info:
  version: 1.0.0
  title: Kids Keeper API Docs
  description: Kids Keeper API 문서
  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - description: dev servers
    url: "http://localhost:3000/api/"
paths:
  /districts:
    get:
      tags:
        - district
      summary: get all districts
      description: null
      parameters:
        - name: parent_code
          in: query
          required: false
          description: 상위 행정구역 코드
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                    name:
                      type: string
                    parent_code:
                      type: string
                    count:
                      type: string
  "/districts/{code}":
    get:
      tags:
        - district
      summary: get district by code
      description: null
      parameters:
        - name: code
          in: path
          required: true
          description: 행정구역 코드
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  name:
                    type: string
                  parent_code:
                    type: string
                  count:
                    type: string
  "/districts/{name}":
    get:
      tags:
        - district
      summary: get district by name
      description: null
      parameters:
        - name: name
          in: path
          required: true
          description: 행정구역 이름
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  name:
                    type: string
                  parent_code:
                    type: string
                  count:
                    type: string
  /centers:
    get:
      tags:
        - children care center
      summary: get all centers
      description: null
      parameters:
        - name: code
          in: query
          required: false
          description: 행정구역 코드
        - name: name
          in: query
          required: false
          description: 행정구역 이름
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    center_id:
                      type: integer
                    name:
                      type: string
                    lat:
                      type: string
                    lng:
                      type: string
                    district_code:
                      type: string
                    district_name:
                      type: string
  "/centers/{center_id}":
    get:
      tags:
        - children care center
      summary: get center by center id
      description: null
      parameters:
        - name: center_id
          in: path
          required: true
          description: 어린이집 ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  center_id:
                    type: integer
                  name:
                    type: string
                  lat:
                    type: string
                  lng:
                    type: string
                  district_code:
                    type: string
                  district_name:
                    type: string
  "/centers/{center_name}":
    get:
      tags:
        - children care center
      summary: get center by name
      description: null
      parameters:
        - name: center_name
          in: path
          required: true
          description: 어린이집 이름
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  center_id:
                    type: integer
                  name:
                    type: string
                  lat:
                    type: string
                  lng:
                    type: string
                  district_code:
                    type: string
                  district_name:
                    type: string
  /areas:
    get:
      tags:
        - area
      summary: get all areas
      description: null
      parameters:
        - name: center_id
          in: query
          required: false
          description: 어린이집 id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    area_id:
                      type: integer
                    area_name:
                      type: string
                    use_of_area:
                      type: string
                    center_id:
                      type: integer
  "/areas/{area_id}":
    get:
      tags:
        - area
      summary: get area by area id
      description: null
      parameters:
        - name: area_id
          in: path
          required: true
          description: 촬영구역 ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  area_id:
                    type: integer
                  area_name:
                    type: string
                  use_of_area:
                    type: string
                  center_id:
                    type: integer
  /cctvs:
    get:
      tags:
        - cctv
      summary: get all cctvs
      description: null
      parameters:
        - name: area_id
          in: query
          required: false
          description: 촬영구역 id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    cctv_id:
                      type: integer
                    quaity:
                      type: string
                    install_date:
                      type: date
                    uninstall_date:
                      type: date
                    area_id:
                      type: integer
  "/cctvs/{cctv_id}":
    get:
      tags:
        - cctv
      summary: get cctv by cctv id
      description: null
      parameters:
        - name: cctv_id
          in: path
          required: true
          description: CCTV id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  cctv_id:
                    type: integer
                  quaity:
                    type: string
                  install_date:
                    type: date
                  uninstall_date:
                    type: date
                  area_id:
                    type: integer
  /videos:
    get:
      tags:
        - video
      summary: get all videos
      description: null
      parameters:
        - name: cctv_id
          in: query
          required: false
          description: CCTV id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    video_id:
                      type: integer
                    record_date:
                      type: date
                    delete_date:
                      type: date
                    delete_issue:
                      type: string
                    storage_name:
                      type: string
                    cctv_id:
                      type: integer
  "/videos/{video_id}":
    get:
      tags:
        - video
      summary: get video by video id
      description: null
      parameters:
        - name: video_id
          in: path
          required: true
          description: 비디오 id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  video_id:
                    type: integer
                  record_date:
                    type: date
                  delete_date:
                    type: date
                  delete_issue:
                    type: string
                  storage_name:
                    type: string
                  cctv_id:
                    type: integer
  /anomalies:
    get:
      tags:
        - anomaly
      summary: get all anomalies
      description: null
      parameters:
        - name: video_id
          in: query
          required: false
          description: 비디오 id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ano_id:
                      type: integer
                    start_time:
                      type: date
                    end_time:
                      type: date
                    follow_up:
                      type: string
                    video_id:
                      type: integer
  "/anomalies/{anomaly_id}":
    get:
      tags:
        - anomaly
      summary: get anomaly by anomaly id
      description: null
      parameters:
        - name: anomaly_id
          in: path
          required: false
          description: 이상행동감지 id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ano_id:
                    type: integer
                  start_time:
                    type: date
                  end_time:
                    type: date
                  follow_up:
                    type: string
                  video_id:
                    type: integer
tags:
  - name: district
  - name: children care center
  - name: area
  - name: cctv
  - name: video
  - name: anomaly
