openapi: 3.0.0
info:
  version: 1.0.0
  title: Kids Keeper API Docs
  description: Kids Keeper API 문서
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: localhost
    url: 'http://localhost:3000/api/'
paths:
  /districts:
    get:
      tags:
        - district
      summary: get all districts
      description: null
      parameters:
        - name: parent_code
          in: query
          required: false
          description: 상위 행정구역 코드
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    district_code:
                      type: string
                    district_name:
                      type: string
                    parent_code:
                      type: string
                    assualt_count:
                      type: integer
                    fight_count:
                      type: integer
                    swoon_count:
                      type: integer
                    anomaly_count:
                      type: integer
  '/districts/{district_code}':
    get:
      tags:
        - district
      summary: get district by district code
      description: null
      parameters:
        - name: district_code
          in: path
          required: true
          description: 행정구역 코드
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    district_code:
                      type: string
                    district_name:
                      type: string
                    parent_code:
                      type: string
                    assualt_count:
                      type: integer
                    fight_count:
                      type: integer
                    swoon_count:
                      type: integer
                    anomaly_count:
                      type: integer
  /centers:
    get:
      tags:
        - children care center
      summary: get all centers
      description: null
      parameters:
        - name: district_code
          in: query
          required: true
          description: 행정구역 코드
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    center_id:
                      type: integer
                    center_name:
                      type: string
                    operation_type:
                      type: string
                    operation_status:
                      type: string
                    zipcode:
                      type: string
                    address:
                      type: string
                    center_phone:
                      type: string
                    fax:
                      type: string
                    web_page:
                      type: string
                    latitude:
                      type: string
                    longtitude:
                      type: string
                    district_code:
                      type: string
                    district_name:
                      type: string
                    assault_count:
                      type: integer
                    fight_count:
                      type: integer
                    swoon_count:
                      type: integer
                    anomaly_count:
                      type: integer
  '/centers/{center_id}':
    get:
      tags:
        - children care center
      summary: get center by center id
      description: null
      parameters:
        - name: center_id
          in: path
          required: true
          description: 어린이집 ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  center_id:
                    type: integer
                  center_name:
                    type: string
                  operation_type:
                    type: string
                  operation_status:
                    type: string
                  zipcode:
                    type: string
                  address:
                    type: string
                  center_phone:
                    type: string
                  fax:
                    type: string
                  web_page:
                    type: string
                  latitude:
                    type: string
                  longtitude:
                    type: string
                  district_code:
                    type: string
                  district_name:
                    type: string
                  assault_count:
                    type: integer
                  fight_count:
                    type: integer
                  swoon_count:
                    type: integer
                  anomaly_count:
                    type: integer
  /cctvs:
    get:
      tags:
        - cctv
      summary: get all cctvs
      description: null
      parameters:
        - name: list_size
          in: query
          required: true
          description: 페이지 내 데이터 개수
        - name: range
          in: query
          required: true
          description: 현재 페이지의 범위
        - name: page
          in: query
          required: true
          description: 현재 범위 내 페이지
        - name: type
          in: query
          required: false
          description: 검색할 유형 (컬럼)
        - name: keyword
          in: query
          required: false
          description: 검색할 키워드
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    cctv_id:
                      type: integer
                    cctv_name:
                      type: string
                    cctv_mac:
                      type: string
                    quaity:
                      type: string
                    install_date:
                      type: string
                      format: date
                    uninstall_date:
                      type: string
                      format: date
                    center_id:
                      type: integer
                    center_name:
                      type: string
                    address:
                      type: string
    post:
      tags:
        - cctv
      summary: create cctv
      description: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                center_id:
                  type: integer
                cctv_name:
                  type: string
                cctv_mac:
                  type: string
                install_date:
                  type: string
                  format: date
                uninstall_date:
                  type: string
                  format: date
                quality:
                  type: string
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                type: object
                properties:
                  cctv_id:
                    type: integer
                  cctv_name:
                    type: string
                  cctv_mac:
                    type: string
                  install_date:
                    type: string
                    format: date
                  uninstall_date:
                    type: string
                    format: date
                  quality:
                    type: string
                  center_id:
                    type: integer
  '/cctvs/{cctv_mac}':
    put:
      tags:
        - cctv
      summary: update cctv by cctv_mac
      description: null
      parameters:
        - name: cctv_mac
          in: path
          required: true
          description: CCTV MAC 주소
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cctv_name:
                  type: string
                install_date:
                  type: string
                  format: date
                uninstall_date:
                  type: string
                  format: date
                quality:
                  type: string
      responses:
        '200':
          description: UPDATED
          content:
            application/json:
              schema:
                type: object
                properties:
                  cctv_id:
                    type: integer
                  cctv_name:
                    type: string
                  install_date:
                    type: string
                    format: date
                  uninstall_date:
                    type: string
                    format: date
                  quality:
                    type: string
                  center_id:
                    type: integer
    delete:
      tags:
        - cctv
      summary: delete cctv by cctv_mac
      description: null
      parameters:
        - name: cctv_mac
          in: path
          required: true
          description: CCTV MAC 주소
      responses:
        '204':
          description: DELETE
  /anomalies/logs:
    get:
      tags:
        - anomaly log
      summary: get all anomaly logs
      description: null
      parameters:
        - name: list_size
          in: query
          required: true
          description: 페이지 내 데이터 개수
        - name: range
          in: query
          required: true
          description: 현재 페이지의 범위
        - name: page
          in: query
          required: true
          description: 현재 범위 내 페이지
        - name: type
          in: query
          required: false
          description: 검색할 유형 (컬럼)
        - name: keyword
          in: query
          required: false
          description: 검색할 키워드
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    anomaly_log_id:
                      type: integer
                    center_name:
                      type: string
                    address:
                      type: string
                    record_date:
                      type: string
                      format: date
                    anomaly_type:
                      type: string
    post:
      tags:
        - anomaly log
      summary: create anomaly log
      description: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                video:
                  type: object
                  properties:
                    record_date:
                      type: string
                      format: date
                    cctv_mac:
                      type: string
                    storage_name:
                      type: string
                anomaly_type:
                  type: string
                start_time:
                  type: string
                  format: date
                end_time:
                  type: string
                  format: date
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                type: object
                properties:
                  anomaly_id:
                    type: integer
                  video_id:
                    type: integer
                  anomaly_type:
                    type: string
                  start_time:
                    type: string
                    format: date
                  end_time:
                    type: string
                    format: date
                  follow_up:
                    type: string
  /anomalies/logs/recent:
    get:
      tags:
        - anomaly log
      summary: get recent anomaly logs
      description: null
      parameters:
        - name: list_size
          in: query
          required: true
          description: 페이지 내 데이터 개수
        - name: range
          in: query
          required: true
          description: 현재 페이지의 범위
        - name: page
          in: query
          required: true
          description: 현재 범위 내 페이지
        - name: type
          in: query
          required: false
          description: 검색할 유형 (컬럼)
        - name: keyword
          in: query
          required: false
          description: 검색할 키워드
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    anomaly_log_id:
                      type: integer
                    center_name:
                      type: string
                    address:
                      type: string
                    record_date:
                      type: string
                      format: date
                    anomaly_type:
                      type: string
  /auth/register:
    post:
      tags:
        - auth
      summary: login with member
      description: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                member_id:
                  type: string
                password:
                  type: string
                member_name:
                  type: string
                member_phone:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /auth/login:
    post:
      tags:
        - auth
      summary: login
      description: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                member_id:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  member_id:
                    type: string
                  member_name:
                    type: string
                  member_phone:
                    type: string
                  email:
                    type: string
  /auth/member:
    put:
      tags:
        - auth
      summary: update member
      description: null
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                member_name:
                  type: string
                member_phone:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /auth/valid:
    get:
      tags:
        - auth
      summary: check if JWT is valid
      description: null
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
tags:
  - name: district
  - name: children care center
  - name: cctv
  - name: anomaly log
  - name: auth
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
