name: Lint Action - JS

on: [push, pull_request]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory : ./BE
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}
          CI: true

      - name: Run Build
        working-directory : ./BE
        run: yarn build

      - name: Run Tests
        working-directory : ./BE
        run: yarn run test:ci

      # ESLint and Prettier must be in `package.json`
      - name: Run JavaScript linters
        uses: wearerequired/lint-action@v1
        with:
          working-directory : ./BE
          eslint: true
          prettier: true
